# Generated by Django 2.2.3 on 2019-10-20 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='api.Factory'),
        ),
    ]
