# Generated by Django 2.2.4 on 2019-11-08 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_change_factory_image_relate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='api.Factory'),
        ),
    ]
