# Generated by Django 2.2.4 on 2019-11-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_factory_status_default_A_20191108_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='status_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
