# Generated by Django 2.2.4 on 2019-12-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191122_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrecord',
            name='nickname',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
