# Generated by Django 2.2.10 on 2020-04-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200212_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='towncode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='factory',
            name='townname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
