# Generated by Django 2.2.10 on 2020-04-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200411_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='sectcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='factory',
            name='sectname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
