# Generated by Django 2.2.10 on 2020-04-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_init_town_sect_name_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='orig_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='orig_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
