# Generated by Django 2.2.10 on 2020-04-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200425_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='cet_report_status',
            field=models.CharField(choices=[('A', '未舉報'), ('O', '第一次發文待回覆'), ('P', '第一次發文已播電話追蹤'), ('Q', '第一次回文'), ('X', '第二次發文待回覆'), ('Y', '第二次發文已播電話追蹤'), ('Z', '第二次回文'), ('B', '已結案')], default='A', max_length=1),
        ),
    ]
