# Generated by Django 2.2.13 on 2020-07-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_document_followup_govagency_recycleddocument_recycledfactory_recycledfollowup_recycledimage_recycled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='cet_report_status',
            field=models.CharField(choices=[('A', '尚未審查'), ('O', '已審查-不檢舉'), ('P', '已審查-需補件'), ('Q', '已審查-待檢舉'), ('X', '已審查-已生成公文')], default='A', max_length=1),
        ),
    ]
