# Generated by Django 2.2.13 on 2020-07-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200708_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='cet_review_status',
            field=models.CharField(choices=[('A', '尚未審查'), ('O', '已審查-不檢舉'), ('P', '已審查-需補件'), ('Q', '已審查-待檢舉'), ('X', '已審查-已生成公文')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='factory',
            name='cet_report_status',
            field=models.CharField(choices=[('A', '未舉報'), ('O', '第一次發文待回覆'), ('P', '第一次發文已播電話追蹤'), ('Q', '第一次回文'), ('X', '第二次發文待回覆'), ('Y', '第二次發文已播電話追蹤'), ('Z', '第二次回文'), ('B', '已結案')], default='A', max_length=1),
        ),
    ]
