# Generated by Django 2.2.13 on 2020-07-21 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200715_1311'),
        ('api', '0020_initial_gov_agency_data'),
    ]

    operations = [
    ]
