# Generated by Django 2.2.13 on 2020-07-15 13:31

from django.db import migrations, models


def forward_func(apps, schema_editor):
    Factory = apps.get_model("api", "Factory")

    factories = Factory.objects.only("created_at").order_by("created_at")

    for number, factory in enumerate(factories):
        factory.display_number = number

    Factory.objects.bulk_update(factories, ["display_number"])


def backward_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_auto_20200822_0649"),
    ]

    operations = [
        migrations.AddField(
            model_name="factory",
            name="display_number",
            field=models.IntegerField(null=True),
        ),
        migrations.RunPython(code=forward_func, reverse_code=backward_func),
        migrations.AlterField(
            model_name="factory",
            name="display_number",
            field=models.IntegerField(unique=True),
        ),
    ]
