# Generated by Django 2.2.13 on 2020-09-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_document_display_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='display_status',
            field=models.IntegerField(choices=[(0, '已檢舉'), (1, '已排程稽查'), (2, '陳述意見期'), (3, '已勒令停工'), (4, '已發函斷電'), (5, '已排程拆除'), (6, '已拆除'), (7, '不再追蹤')], default=0),
        ),
    ]
