# Generated by Django 2.2.13 on 2020-09-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20200923_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='code',
            field=models.IntegerField(help_text='公文號'),
        ),
    ]
