# Generated by Django 2.2.13 on 2020-10-07 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20200927_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='code',
            field=models.IntegerField(verbose_name='公文號'),
        ),
        migrations.RemoveField(
            model_name='followup',
            name='document',
        ),
        migrations.AddField(
            model_name='followup',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='follow_ups', to='api.Document'),
        ),
    ]
