# Generated by Django 2.2.13 on 2020-10-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_update_followup_document_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CETNext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CETReportStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GovResponseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='cet_next_tags',
            field=models.ManyToManyField(blank=True, to='api.CETNext'),
        ),
        migrations.AddField(
            model_name='document',
            name='cet_report_status_tags',
            field=models.ManyToManyField(blank=True, to='api.CETReportStatus'),
        ),
        migrations.AddField(
            model_name='document',
            name='gov_response_status_tags',
            field=models.ManyToManyField(blank=True, to='api.GovResponseStatus'),
        ),
    ]
