# Generated by Django 2.2.13 on 2021-03-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_factory_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='deletehash',
            field=models.TextField(blank=True, help_text='delete hash', null=True),
        ),
    ]
