# Generated by Django 2.2.13 on 2021-06-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_add_image_deletehash'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='building_status',
            field=models.CharField(blank=True, choices=[('A', '既有'), ('B', '新增'), ('C', '興建中'), ('D', '難以判定')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='factory',
            name='highlight_category',
            field=models.CharField(blank=True, choices=[('A', '新廠商寄居'), ('B', '倉儲')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='factory',
            name='usage_status',
            field=models.CharField(blank=True, choices=[('A', '低污染產業'), ('B', '高污染產業'), ('C', '其他用途'), ('D', '難以判定')], max_length=1, null=True),
        ),
    ]
