# Generated by Django 2.2.13 on 2021-09-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20210825_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='display_status',
            field=models.IntegerField(choices=[(0, '已檢舉'), (1, '已排程稽查'), (2, '陳述意見期'), (3, '已勒令停工'), (4, '已發函斷電'), (5, '已排程拆除'), (6, '已拆除'), (7, '等待新事證')], db_index=True, default=0),
        ),
    ]
