# Generated by Django 2.2.13 on 2021-10-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20210825_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='for_user',
            field=models.BooleanField(default=False),
        ),
    ]
