# Generated by Django 2.2.13 on 2021-10-20 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_followup_for_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportrecord',
            name='user_ip',
        ),
    ]
