version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/Disfactory
    ports:
      - ${DISFACTORY_BACKEND_PORT}:8000
    depends_on:
      - db
    environment:
      DISFACTORY_BACKEND_DEFAULT_DB_NAME: ${DISFACTORY_BACKEND_DEFAULT_DB_NAME}
      DISFACTORY_BACKEND_DEFAULT_DB_USER: ${DISFACTORY_BACKEND_DEFAULT_DB_USER}
      DISFACTORY_BACKEND_DEFAULT_DB_PASSWORD: ${DISFACTORY_BACKEND_DEFAULT_DB_PASSWORD}
      DISFACTORY_BACKEND_DEFAULT_DB_HOST: db
      DISFACTORY_BACKEND_DEFAULT_DB_PORT: 5432  # default port of db image
      DISFACTORY_ALLOWED_HOST: ${DISFACTORY_ALLOWED_HOST}
      DISFACTORY_IMGUR_CLIENT_ID: ''
      DISFACTORY_BACKEND_LOG_LEVEL: ${DISFACTORY_BACKEND_LOG_LEVEL}
      DISFACTORY_BACKEND_MAX_FACTORY_PER_GET: ${DISFACTORY_BACKEND_MAX_FACTORY_PER_GET}
      DISFACTORY_BACKEND_MAX_FACTORY_RADIUS_PER_GET: ${DISFACTORY_BACKEND_MAX_FACTORY_RADIUS_PER_GET}
      DISFACTORY_BACKEND_CORS_ORIGIN_WHITELIST: ${DISFACTORY_BACKEND_CORS_ORIGIN_WHITELIST}
      DISFACTORY_BACKEND_DEBUG: 'true'
    command:
      - /bin/bash
      - -c
      - "/Disfactory/scripts/start.sh"

  db:
    image: postgres:12
    volumes:
      - ${DISFACTORY_PGDATA_PATH}:/var/lib/postgresql/data/
      - ${DISFACTORY_PGDATA_BACKUP_PATH}:/tmp/db_dump/
    ports:
      - ${DISFACTORY_BACKEND_DEFAULT_DB_DEV_PORT}:5432
    environment:
      POSTGRES_DB: ${DISFACTORY_BACKEND_DEFAULT_DB_NAME}
      POSTGRES_USER: ${DISFACTORY_BACKEND_DEFAULT_DB_USER}
      POSTGRES_PASSWORD: ${DISFACTORY_BACKEND_DEFAULT_DB_PASSWORD}

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/Disfactory
    depends_on:
      - db
      - web
    environment:
      DISFACTORY_BACKEND_DEFAULT_DB_NAME: ${DISFACTORY_BACKEND_DEFAULT_DB_NAME}
      DISFACTORY_BACKEND_DEFAULT_DB_USER: ${DISFACTORY_BACKEND_DEFAULT_DB_USER}
      DISFACTORY_BACKEND_DEFAULT_DB_PASSWORD: ${DISFACTORY_BACKEND_DEFAULT_DB_PASSWORD}
      DISFACTORY_BACKEND_DEFAULT_DB_HOST: db
      DISFACTORY_BACKEND_DEFAULT_DB_PORT: 5432  # default port of db image
      DISFACTORY_ALLOWED_HOST: ${DISFACTORY_ALLOWED_HOST}
      DISFACTORY_BACKEND_LOG_LEVEL: ${DISFACTORY_BACKEND_LOG_LEVEL}
      DISFACTORY_IMGUR_CLIENT_ID: ''
      DISFACTORY_BACKEND_DEBUG: 'true'
    command:
      - /bin/bash
      - -c
      - "/Disfactory/scripts/start_worker.sh"
