# Pull base image
FROM python:3.9 AS base

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /Disfactory

RUN apt-get update
RUN apt-get install -y libproj-dev binutils curl

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /usr/local/bin/
COPY pyproject.toml uv.lock ./

# Install Caddy
RUN apt-get install -y debian-keyring debian-archive-keyring apt-transport-https
RUN curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
RUN curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list
RUN apt-get update
RUN apt-get install -y caddy

# Dev image
FROM base AS dev
RUN uv sync --dev
COPY . /Disfactory/
ENV PATH="/Disfactory/.venv/bin:$PATH"

# Prod image with Caddy
FROM base AS prod
RUN uv sync --no-dev
COPY . /Disfactory/
ENV PATH="/Disfactory/.venv/bin:$PATH"

# Create directories for static and media files
RUN mkdir -p /Disfactory/static /Disfactory/images

# Create Caddy configuration directory
RUN mkdir -p /etc/caddy
